### ISSUE TITLE
Cannot extract .tar.xz

### ISSUE THREAD

**Issue by sent44** [kmalakoff/fast-extract#2]
Always show `[Error: ENOENT: no such file or directory, rename 'dist_dir\{random number}' -> 'dist_dir']` when extract `.tar.xz` (didn't test with other types)

and also `dist_dir` folder always disappear every time even with content in it without force option

Windows 10
Node.js v14.10.1

**Comment by sent44** [comment]
Since I already folk/clone so I run the test - 13 pass 14 fail
```
  createWriteStream
    happy path
      √ extract file with progress (84ms)
      √ extract file multiple times
      √ extract file with progress - no basename
      1) extract tar with progress
      2) extract tar multiple times
      3) extract zip with progress
      4) extract zip multiple times
    unhappy path
      √ should fail with too large strip (tar)
      √ should fail with too large strip (zip)

  extensions
    tar
      5) extract file
      6) extract file without type - dot
      7) extract file without type - no dot
      8) extract file without type - options as type, no strip
      9) extract file by stream - filename
      10) extract file by stream - basename

  extract
    happy path
      √ extract file with progress
      √ extract file multiple times
      √ extract file with progress - promise
      11) extract tar with progress
      12) extract tar multiple times
      13) extract zip with progress
      14) extract zip multiple times
    unhappy path
      √ should fail with too large strip (tar) - path
      √ should fail with too large strip (tar) - path - promise
      √ should fail with too large strip (tar) - stream
      √ should fail with too large strip (zip) - path
      √ should fail with too large strip (zip) - stream


  13 passing (758ms)
  14 failing

  1) createWriteStream happy path extract tar with progress:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\createWriteStream.test.js:105:16)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at FSReqCallback.oncomplete (fs.js:164:23)

  2) createWriteStream happy path extract tar multiple times:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\createWriteStream.test.js:120:16)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at FSReqCallback.oncomplete (fs.js:164:23)

  3) createWriteStream happy path extract zip with progress:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\createWriteStream.test.js:159:16)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at node_modules\rimraf\rimraf.js:165:14
      at FSReqCallback.oncomplete (fs.js:164:23)

  4) createWriteStream happy path extract zip multiple times:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\createWriteStream.test.js:176:16)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at node_modules\rimraf\rimraf.js:165:14
      at FSReqCallback.oncomplete (fs.js:164:23)

  5) extensions tar extract file:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\extensions.test.js:34:16)
      at WriteStream.f (node_modules\once\once.js:25:25)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at FSReqCallback.oncomplete (fs.js:164:23)

  6) extensions tar extract file without type - dot:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\extensions.test.js:46:16)
      at WriteStream.f (node_modules\once\once.js:25:25)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at FSReqCallback.oncomplete (fs.js:164:23)

  7) extensions tar extract file without type - no dot:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\extensions.test.js:58:16)
      at WriteStream.f (node_modules\once\once.js:25:25)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at FSReqCallback.oncomplete (fs.js:164:23)

  8) extensions tar extract file without type - options as type, no strip:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\extensions.test.js:70:16)
      at WriteStream.f (node_modules\once\once.js:25:25)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at FSReqCallback.oncomplete (fs.js:164:23)

  9) extensions tar extract file by stream - filename:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\extensions.test.js:84:16)
      at WriteStream.f (node_modules\once\once.js:25:25)
      at WriteStream.onerror (node_modules\end-of-stream\index.js:44:12)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at FSReqCallback.oncomplete (fs.js:164:23)

  10) extensions tar extract file by stream - basename:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\extensions.test.js:98:16)
      at WriteStream.f (node_modules\once\once.js:25:25)
      at WriteStream.onerror (node_modules\end-of-stream\index.js:44:12)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at FSReqCallback.oncomplete (fs.js:164:23)

  11) extract happy path extract tar with progress:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\extract.test.js:96:16)
      at WriteStream.f (node_modules\once\once.js:25:25)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at FSReqCallback.oncomplete (fs.js:164:23)

  12) extract happy path extract tar multiple times:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\extract.test.js:109:16)
      at WriteStream.f (node_modules\once\once.js:25:25)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at FSReqCallback.oncomplete (fs.js:164:23)

  13) extract happy path extract zip with progress:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\extract.test.js:140:16)
      at WriteStream.f (node_modules\once\once.js:25:25)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at node_modules\rimraf\rimraf.js:165:14
      at FSReqCallback.oncomplete (fs.js:164:23)

  14) extract happy path extract zip multiple times:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(!err)

      + expected - actual

      -false
      +true

      at WriteStream.<anonymous> (test\spec\extract.test.js:155:16)
      at WriteStream.f (node_modules\once\once.js:25:25)
      at WriteStream.destroy (node_modules\flush-write-stream\index.js:52:17)
      at lib\createWriteStream.js:57:13
      at lib\createWriteStream.js:25:7
      at callAwait (node_modules\queue-cb\index.js:11:12)
      at queueCallback (node_modules\queue-cb\index.js:20:57)
      at lib\rimrafAll.js:11:58
      at next (node_modules\rimraf\rimraf.js:83:7)
      at CB (node_modules\rimraf\rimraf.js:119:9)
      at node_modules\rimraf\rimraf.js:165:14
      at FSReqCallback.oncomplete (fs.js:164:23)

```

**Comment by kmalakoff** [comment]
Thank you for submitting this issue...

I tried to follow.a similar convention to the `got` library for creating subfolders, but might have gotten it wrong.

1) Can you share with me the exact code that you are using, tell me which folders already exist, and tell me the top level structure of the archive? 

2) Also, if you have forked the library and changed something to make these tests fail, can you provide a link to the commit that I can run to see the changes and modify the tests to fit the use case?
