### ISSUE TITLE
Does not extract all files in a zip file

### ISSUE THREAD

**Issue by niranjan94** [kmalakoff/fast-extract#83]
I'm trying to extract a zip file and most files are not extracted. (Zip file is ~100mb. extracted folder is ~19mb). The file in question is [commandlinetools-mac-11076708_latest.zip](https://developer.android.com/studio#command-line-tools-only)

Using 

```ts
await fastExtract(sourceFilePath, destinationPath);
```

**Comment by JonatanAntoni** [comment]
I am having similar issues right now. I tracked it down into the depth of zip-iterator's ZipExtract:

```
Exception has occurred: Error: unexpected end of file
  at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
    at Zlib.callbackTrampoline (node:internal/async_hooks:130:17)
    at processChunkSync (node:zlib:415:12)
    at zlibBufferSync (node:zlib:178:12)
    at Object.syncBufferWrapper [as inflateRawSync] (node:zlib:767:14)
    at inflateRaw (node_modules/extract-base-iterator/dist/esm/shared/compat.js:195:21)
    at ZipExtract.processDeflateDataDescriptor (node_modules/zip-iterator/dist/esm/zip/ZipExtract.js:391:34)
    at ZipExtract.processFileData (node_modules/zip-iterator/dist/esm/zip/ZipExtract.js:304:29)
```

The error is *not* reported back to the top level call to `fastExtract`:

```ts
await fastExtract(archiveFile, dest, { force: true, ...options }).catch(error => {
    throw new Error('Failed to extract archive', { cause: error });
});
```

I.e., the `catch` handler is not executed. 

This is reproducible on my Mac with MacOS 26, running Node v20.19.5, and the archive at https://github.com/pyocd/pyOCD/releases/download/v0.42.0/pyocd-macos-0.42.0.zip
